
services:
  mongodb:
    image: mongo:7.0
    container_name: pwc_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pwc_network

  redis:
    image: redis:7.2-alpine
    container_name: pwc_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - pwc_network

  mongo-express:
    image: mongo-express:1.0-20-alpine3.18
    container_name: pwc_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
    depends_on:
      - mongodb
    networks:
      - pwc_network

  api:
    build:
      context: .
      dockerfile: ./src/python/projects/api/Dockerfile
    container_name: pwc_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - STORAGE_TYPE=${STORAGE_TYPE}
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - AI_PROVIDER=${AI_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - api_storage:/app/storage
    depends_on:
      - mongodb
      - redis
    networks:
      - pwc_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: ./src/python/projects/analyze_contracts/Dockerfile
    container_name: pwc_worker
    restart: unless-stopped
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - STORAGE_TYPE=${STORAGE_TYPE}
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - AI_PROVIDER=${AI_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_BASE_URL=${API_BASE_URL}
      - PARSING_PROVIDER=${PARSING_PROVIDER}
      - ANALYSIS_PROVIDER=${ANALYSIS_PROVIDER}
      - EVALUATION_PROVIDER=${EVALUATION_PROVIDER}
    volumes:
      - api_storage:/app/storage
    depends_on:
      api:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - pwc_network

  frontend:
    build:
      context: .
      dockerfile: ./src/python/projects/frontend/Dockerfile
    container_name: pwc_frontend
    restart: unless-stopped
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - api
    networks:
      - pwc_network

volumes:
  mongodb_data:
  redis_data:
  api_storage:

networks:
  pwc_network:
    driver: bridge